### PR TITLE
Fixed for latest nightly

### PR DESCRIPTION
**Pull request by gsingh93**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 94838bdbcc4c9aa09154809aeeb43f8eed1a30bb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/deuterium-orm/deuterium/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by gsingh93** [comment]
What would the type/scope be? `fix(lib)`?

**Comment by s-panferov** [comment]
@gsingh93 thanks for your work! Yes, `lib` or `*` will be ok.

**Comment by gsingh93** [comment]
Ok, I amended the commit message. If you could look into fixing `deuterium_orm` too, that'd be great. The errors there were a bit more involved.

**Comment by s-panferov** [comment]
@gsingh93 thanks again for your work! I'll try to fix everything today.

**Pull request merged**
