### PR TITLE
feat(lib): Added MysqlAdapter

### PR DESCRIPTION
**Pull request by gsingh93**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 408f3a332b3d0e60aabeee61197784a4a4572569
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/deuterium-orm/deuterium/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by gsingh93** [comment]
@s-panferov It looks like you need to update your travis file to [use the nightly](http://docs.travis-ci.com/user/languages/rust/), or alternatively remove the unstable features.

**Comment by s-panferov** [comment]
@gsingh93 sorry for the delay, I'll try to merge this soon

**Comment by gsingh93** [comment]
ping @s-panferov. Would you like me to make the travis fixes as well?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 408f3a332b3d0e60aabeee61197784a4a4572569
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 14d641c6e08578d1bb7367c7e6f749494e73f063
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/deuterium-orm/deuterium/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by gsingh93** [comment]
Instead of fixing Travis, I removed the unstable features, which weren't necessary anyway.

**Comment by s-panferov** [comment]
@gsingh93 thanks!

**Pull request merged**
